language: node_js
node_js:
  - '10'
addons:
  apt:
    sources:
      - google-chrome
    packages:
      - google-chrome-stable
script:
  - npm run build
  - npm run test.ci
before_deploy:
  - cp README.md LICENSE dist/config
  - cd dist/config
deploy:
  provider: npm
  email: $NPM_EMAIL
  api_key: $NPM_API_KEY
  skip_cleanup: true
  on:
    tags: true
